# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information_sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email1', models.EmailField(blank=True, max_length=254)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email2', models.EmailField(blank=True, max_length=254)),
                ('inputDate', models.DateField(default=datetime.datetime.today)),
                ('verifyDate', models.DateField(default=datetime.datetime.today)),
                ('fromDate', models.DateField(default=datetime.datetime.today)),
                ('fromSource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information_sources.InformationSource')),
            ],
        ),
    ]
